version: 1.0
app:
  # number of instances
  instances:
    # q: consider availability zones? 

    # min number of instances. can be 0 for scale to 0. default to 1.
    min: 1
    # max number of instances. defaults to 1 if min == 0, otherwise defaults to min
    # q: what's the overall limit?
    max: 1
  resources:
    # max cpu, defaults to 1 cpu limit, half of that for min, min >= 1
    # q: what's the overall limit?
    # q: do we support fractions?
    cpu: 1
    # memory limit is based on cpu value: 1:3 memory ratio, e.g. 1 cpu == 3 gb
    # ephemeral disk limit will be set to 1GB  
  # List of environment variables that set for the application
  # Liberty encrypted values are supported only if referenced in server.xml
 
  
  # version:
  version: "ca7547bc-7906-46d5-9b83-e526f6ea15cc"
  endpoints: public
